<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    '9c97f69f54efdfabb5462f360f97a39d' => $vendorDir . '/typo3/autoload-include.php',
);
