# Load default processing options
imports:
  - { resource: "EXT:sem_content/Configuration/RTE/Shared.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

editor:
  config:
    stylesSet:
      # Anchor tag styles
      # - { name: "btn-default", element: "a", attributes: { class: "btn-default"} }

    format_tags: "p;h1;h2;h3;h4;h5;h6"

    toolbarGroups:
      - { name: styles, groups: [ format, styles ] }
      - { name: basicstyles, groups: [ basicstyles ] }
      - { name: paragraph, groups: [ list, align ] }
      - { name: links, groups: [ links ] }
      - { name: clipboard, groups: [ cleanup, find, undo ] }
      - { name: tools, groups: [ specialchar ] }
      - { name: document, groups: [ mode ] }

    extraPlugins:
      - justify